# Generated by Django 2.2.2 on 2020-03-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym', models.IntegerField()),
                ('series', models.CharField(max_length=30)),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totqty', models.IntegerField()),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
