# Generated by Django 2.2.2 on 2020-03-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_saved',
            name='sym',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
