# Generated by Django 2.2.2 on 2020-03-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200305_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_saved',
            name='data',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
